# Generated by Django 5.2.6 on 2025-09-23 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando el usuario aceptó los términos y condiciones', null=True, verbose_name='Términos aceptados'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato válido: +5939XXXXXXXX o 09XXXXXXXX', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa +5939XXXXXXXX o 09XXXXXXXX.', regex='^(\\+?593|0)?9\\d{8}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
