# Generated by Django 5.2.6 on 2025-09-28 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato válido: +5939XXXXXXXX o 09XXXXXXXX', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa formato internacional: +[código país][número], ej. +14155552671.', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='Teléfono'),
        ),
    ]
