# Generated by Django 5.2.6 on 2025-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Desmarcar para no recibir emails de premios ganados', verbose_name='Recibir notificaciones'),
        ),
    ]
