# Generated by Django 5.2.6 on 2025-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_new_roulettes',
            field=models.BooleanField(default=True, help_text='Recibir emails cuando se crean nuevas ruletas disponibles', verbose_name='Notificar nuevas ruletas'),
        ),
    ]
