# Generated by Django 5.2.6 on 2025-10-05 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_notify_new_roulettes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(help_text='Formato válido: +5939XXXXXXXX o 09XXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa formato internacional: +[código país][número], ej. +14155552671.', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='Teléfono'),
        ),
    ]
