# Generated by Django 5.2.6 on 2025-09-16 05:48

import django.core.validators
import participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(help_text='Formatos permitidos: JPG, JPEG, PNG, PDF', upload_to=participants.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Comprobante')),
                ('participant_number', models.PositiveIntegerField(db_index=True, editable=False, help_text='Número secuencial del participante dentro de esta ruleta', verbose_name='Número de Participante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Participación')),
                ('is_winner', models.BooleanField(db_index=True, default=False, help_text='Indica si esta participación resultó ganadora', verbose_name='Es Ganador')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['participant_number'],
            },
        ),
    ]
