# Generated by Django 5.2.6 on 2025-09-16 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('roulettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='roulettes.roulette', verbose_name='Ruleta'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['roulette', 'created_at'], name='participant_roulett_8f3399_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'created_at'], name='participant_user_id_5531c3_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['roulette', 'is_winner'], name='participant_roulett_b3b8fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('user', 'roulette'), name='unique_participation_per_user_and_roulette'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('roulette', 'participant_number'), name='unique_participant_number_per_roulette'),
        ),
    ]
