# Generated by Django 5.2.6 on 2025-09-14 05:36

import django.core.validators
import participants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('roulettes', '0002_rouletteprize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='participation',
            name='is_winner',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si esta participación resultó ganadora', verbose_name='Es Ganador'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant_number',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Número secuencial del participante dentro de esta ruleta', verbose_name='Número de Participante'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='receipt',
            field=models.FileField(help_text='Formatos permitidos: JPG, JPEG, PNG, PDF', upload_to=participants.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Comprobante'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('user', 'roulette'), name='unique_participation_per_user_and_roulette'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('roulette', 'participant_number'), name='unique_participant_number_per_roulette'),
        ),
    ]
