# Generated by Django 5.2.6 on 2025-09-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('roulettes', '0006_alter_drawhistory_options_alter_roulette_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='prize_position',
            field=models.PositiveIntegerField(blank=True, help_text='Posición del premio ganado (1°, 2°, 3°, etc.)', null=True, verbose_name='Posición del Premio'),
        ),
        migrations.AddField(
            model_name='participation',
            name='won_prize',
            field=models.ForeignKey(blank=True, help_text='Premio específico que ganó este participante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_participations', to='roulettes.rouletteprize', verbose_name='Premio Ganado'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['won_prize'], name='participant_won_pri_41ba85_idx'),
        ),
    ]
