# Generated by Django 5.2.6 on 2025-09-29 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participation_prize_position_participation_won_prize_and_more'),
        ('roulettes', '0006_alter_drawhistory_options_alter_roulette_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='won_at',
            field=models.DateTimeField(blank=True, help_text='Momento exacto en que ganó el sorteo', null=True, verbose_name='Fecha de Victoria'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Participación'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['won_at'], name='participant_won_at_c7eb3d_idx'),
        ),
    ]
