# Generated by Django 5.2.6 on 2025-11-03 04:58

import django.core.validators
import participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participation_won_at_alter_participation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='receipt',
            field=models.FileField(blank=True, help_text='Formatos permitidos: JPG, JPEG, PNG, PDF', null=True, upload_to=participants.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Comprobante'),
        ),
    ]
