# Generated by Django 5.2.6 on 2025-11-07 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participation_receipt'),
        ('roulettes', '0008_roulettesettings_require_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'roulette'], name='participant_user_id_274ee0_idx'),
        ),
    ]
