# Generated by Django 5.2.6 on 2025-10-03 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True, default='', help_text='Mensaje de error si el envío falló'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_recipient',
            field=models.EmailField(blank=True, default='', help_text='Email del destinatario', max_length=254),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indica si se envió email de esta notificación'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de envío del email', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_sent', 'created_at'], name='notificatio_email_s_445e2f_idx'),
        ),
    ]
