# Generated by Django 5.2.6 on 2025-10-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_email_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_admin_only',
            field=models.BooleanField(default=False, help_text='Si es True, solo visible para administradores (estado de lectura en NotificationReadStatus)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída (solo para notificaciones con user)'),
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Lectura',
                'verbose_name_plural': 'Estados de Lectura',
                'db_table': 'notification_read_statuses',
                'indexes': [models.Index(fields=['notification', 'user'], name='notificatio_notific_16f775_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_5539a1_idx')],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
