# Generated by Django 5.2.6 on 2025-09-09 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('scheduled_date', models.DateTimeField(help_text='Fecha y hora cuando se ejecutará el sorteo automáticamente', verbose_name='Fecha programada del sorteo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_drawn', models.BooleanField(default=False, help_text='Indica si ya se realizó el sorteo de esta ruleta', verbose_name='Sorteo Realizado')),
                ('drawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del sorteo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_roulettes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('drawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn_roulettes', to=settings.AUTH_USER_MODEL, verbose_name='Sorteo realizado por')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_roulettes', to='participants.participation', verbose_name='Participación Ganadora')),
            ],
            options={
                'verbose_name': 'Ruleta',
                'verbose_name_plural': 'Ruletas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], max_length=20, verbose_name='Tipo de sorteo')),
                ('participants_count', models.PositiveIntegerField(verbose_name='Número de participantes')),
                ('drawn_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del sorteo')),
                ('random_seed', models.CharField(blank=True, max_length=100, verbose_name='Semilla aleatoria')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('drawn_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sorteado por')),
                ('winner_selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participation', verbose_name='Participación Ganadora')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_history', to='roulettes.roulette')),
            ],
            options={
                'verbose_name': 'Historial de sorteo',
                'verbose_name_plural': 'Historiales de sorteos',
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.CreateModel(
            name='RouletteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participants', models.PositiveIntegerField(default=5000, help_text='Máximo número de participantes permitidos (RNF2.2)', verbose_name='Máximo participantes')),
                ('allow_multiple_entries', models.BooleanField(default=False, help_text='Si un usuario puede participar múltiples veces', verbose_name='Permitir múltiples participaciones')),
                ('auto_draw_enabled', models.BooleanField(default=True, help_text='Si se debe ejecutar el sorteo automáticamente', verbose_name='Sorteo automático habilitado')),
                ('draw_animation_duration', models.PositiveIntegerField(default=5, help_text='Tiempo de animación del sorteo', verbose_name='Duración animación (segundos)')),
                ('notify_on_participation', models.BooleanField(default=True, verbose_name='Notificar participaciones')),
                ('notify_on_winner', models.BooleanField(default=True, verbose_name='Notificar ganador')),
                ('roulette', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='roulettes.roulette')),
            ],
            options={
                'verbose_name': 'Configuración de ruleta',
                'verbose_name_plural': 'Configuraciones de ruletas',
            },
        ),
        migrations.AddIndex(
            model_name='roulette',
            index=models.Index(fields=['status', 'scheduled_date'], name='roulettes_r_status_a0d454_idx'),
        ),
        migrations.AddIndex(
            model_name='roulette',
            index=models.Index(fields=['is_drawn', 'created_at'], name='roulettes_r_is_draw_8f0f57_idx'),
        ),
    ]
