# Generated by Django 5.2.6 on 2025-09-13 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoulettePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='prizes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='roulettes.roulette')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
