# Generated by Django 5.2.6 on 2025-09-22 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('roulettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettesettings',
            name='winners_target',
            field=models.PositiveIntegerField(default=1, help_text='La ruleta se cierra automáticamente cuando se alcance esta cantidad de ganadores.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de ganadores para cerrar'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_roulettes', to='participants.participation', verbose_name='Ganador (legado / primer ganador)'),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del Premio'),
        ),
    ]
