# Generated by Django 5.2.6 on 2025-09-14 05:36

import django.db.models.deletion
import django.utils.timezone
import roulettes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participation_unique_together_and_more'),
        ('roulettes', '0002_rouletteprize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawhistory',
            options={'ordering': ['-drawn_at']},
        ),
        migrations.AlterModelOptions(
            name='roulettesettings',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='roulette',
            name='roulettes_r_status_a0d454_idx',
        ),
        migrations.RemoveIndex(
            model_name='roulette',
            name='roulettes_r_is_draw_8f0f57_idx',
        ),
        migrations.RemoveField(
            model_name='drawhistory',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='rouletteprize',
            name='title',
        ),
        migrations.RemoveField(
            model_name='roulettesettings',
            name='auto_draw_enabled',
        ),
        migrations.RemoveField(
            model_name='roulettesettings',
            name='draw_animation_duration',
        ),
        migrations.RemoveField(
            model_name='roulettesettings',
            name='notify_on_participation',
        ),
        migrations.RemoveField(
            model_name='roulettesettings',
            name='notify_on_winner',
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='name',
            field=models.CharField(default='Premio', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rouletteprize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='draw_type',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='drawn_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='drawn_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='random_seed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='drawhistory',
            name='winner_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_history', to='participants.participation'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roulettes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='drawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='drawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roulettes_drawn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_roulettes', to='participants.participation'),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=roulettes.models.prize_image_upload_path),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='allow_multiple_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin límite'),
        ),
    ]
