# Generated by Django 5.2.6 on 2025-09-22 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0002_roulettesettings_winners_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettesettings',
            name='winners_target',
            field=models.PositiveIntegerField(default=0, help_text='0 = automático (suma de stock disponible); >0 = valor fijo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de ganadores para cerrar'),
        ),
    ]
