# Generated by Django 5.2.6 on 2025-09-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0003_alter_roulettesettings_winners_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rouletteprize',
            name='probability',
        ),
    ]
