# Generated by Django 5.2.6 on 2025-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0004_remove_rouletteprize_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulettesettings',
            name='auto_draw_when_full',
        ),
        migrations.AlterField(
            model_name='roulette',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de referencia/contador; la ejecución es manual', null=True, verbose_name='Fecha Programada del Sorteo'),
        ),
    ]
