# Generated by Django 5.2.6 on 2025-09-23 19:21

import django.core.validators
import django.db.models.deletion
import roulettes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('roulettes', '0005_remove_roulettesettings_auto_draw_when_full_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawhistory',
            options={'ordering': ['-drawn_at']},
        ),
        migrations.AlterModelOptions(
            name='roulette',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rouletteprize',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='roulette',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=roulettes.models.roulette_cover_upload_path, verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roulettes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='drawn_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='drawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roulettes_drawn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Título de la Ruleta'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='participation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='participation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_roulettes', to='participants.participation'),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=roulettes.models.prize_image_upload_path),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='rouletteprize',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='allow_multiple_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='notify_on_draw',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='notify_on_participation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='show_countdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='winners_target',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
