# Generated by Django 5.2.6 on 2025-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0006_alter_drawhistory_options_alter_roulette_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteprize',
            name='pickup_instructions',
            field=models.TextField(blank=True, default='', help_text='Información sobre cómo y dónde retirar el premio', verbose_name='Instrucciones de retiro'),
        ),
    ]
