# Generated by Django 5.2.6 on 2025-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulettes', '0007_rouletteprize_pickup_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettesettings',
            name='require_receipt',
            field=models.BooleanField(default=True, help_text='¿Los participantes deben adjuntar comprobante de participación?', verbose_name='Requiere comprobante'),
        ),
    ]
